-- ============================================================================
-- Session 1 — 02: COPY INTO raw tables from the internal stage
-- ============================================================================
-- Files are PUT by python/generate_and_load.py into @RAW_STAGE.
-- Role: FR_DATA_ENGINEER | Warehouse: WH_INGESTION_XSMALL
-- ============================================================================

-- Idempotent re-runs: raw landing tables are reloaded from scratch
-- (dbt rebuilds all downstream models either way).
TRUNCATE TABLE SUPERINTENDENCY_DEMO_DB.STAGING_SCHEMA.CLIENTES;
TRUNCATE TABLE SUPERINTENDENCY_DEMO_DB.STAGING_SCHEMA.TARJETAS_CREDITO;
TRUNCATE TABLE SUPERINTENDENCY_DEMO_DB.STAGING_SCHEMA.TRANSACCIONES;

COPY INTO SUPERINTENDENCY_DEMO_DB.STAGING_SCHEMA.CLIENTES
    (RUT, NOMBRE, APELLIDO, FECHA_NACIMIENTO, SEXO, EMAIL, TELEFONO, CIUDAD, REGION, ESTADO, FECHA_ALTA)
FROM @SUPERINTENDENCY_DEMO_DB.STAGING_SCHEMA.RAW_STAGE
FILE_FORMAT = (FORMAT_NAME = SUPERINTENDENCY_DEMO_DB.STAGING_SCHEMA.RAW_CSV_FORMAT)
PATTERN = 'clientes.*'
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO SUPERINTENDENCY_DEMO_DB.STAGING_SCHEMA.TARJETAS_CREDITO
    (ID_TARJETA, RUT, NUMERO_TARJETA, TIPO, LIMITE_CREDITO, FECHA_EMISION, FECHA_VENCIMIENTO, ESTADO, UNIDAD_NEGOCIO)
FROM @SUPERINTENDENCY_DEMO_DB.STAGING_SCHEMA.RAW_STAGE
FILE_FORMAT = (FORMAT_NAME = SUPERINTENDENCY_DEMO_DB.STAGING_SCHEMA.RAW_CSV_FORMAT)
PATTERN = 'tarjetas_credito.*'
ON_ERROR = 'ABORT_STATEMENT';

COPY INTO SUPERINTENDENCY_DEMO_DB.STAGING_SCHEMA.TRANSACCIONES
    (ID_TRANSACCION, ID_TARJETA, RUT, FECHA_TRANSACCION, MONTO, CATEGORIA, COMERCIO, CIUDAD, ESTADO, UNIDAD_NEGOCIO)
FROM @SUPERINTENDENCY_DEMO_DB.STAGING_SCHEMA.RAW_STAGE
FILE_FORMAT = (FORMAT_NAME = SUPERINTENDENCY_DEMO_DB.STAGING_SCHEMA.RAW_CSV_FORMAT)
PATTERN = 'transacciones.*'
ON_ERROR = 'ABORT_STATEMENT';

-- Idempotency: remove loaded files so a re-run re-loads cleanly
REMOVE @SUPERINTENDENCY_DEMO_DB.STAGING_SCHEMA.RAW_STAGE pattern='.*csv.gz';
